services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/app
      - expo-node-modules:/app/node_modules
      - expo-cache:/root/.cache
    environment:
      EXPO_NO_INTERACTIVE: "1"
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "1"
    command: yarn start --tunnel
    stdin_open: true
    tty: true

volumes:
  expo-node-modules:
  expo-cache:
