import { colors } from "./colors";

export const darkColors = {
  background: colors.tertiary950,
  text: colors.neutral50,
  tabIcon: colors.tertiary500,
  tabIconFocused: colors.primary500,
  card: colors.tertiary900,
  cardSecondary: colors.tertiary900,
  border: colors.tertiary700,
  icon: colors.neutral50,
  enabled: colors.primary600,
  disabled: colors.tertiary900,
  light: colors.neutral950,
  dark: colors.neutral50,
  lightGreen: colors.darkGreen,
  mediumGreen: colors.mediumGreen,
  darkGreen: colors.lightGreen,
  lightBlue: colors.darkBlue,
  mediumBlue: colors.mediumBlue,
  darkBlue: colors.lightBlue,
  lightRed: colors.lightRed,
  mediumRed: colors.mediumRed,
  darkRed: colors.darkRed,
  info: colors.info,
  success: colors.success,
  warning: colors.warning,
  danger: colors.danger,
  white: colors.white,
  black: colors.black,
  tintColor: colors.tintColorDark,
  gold: colors.gold,
  cardBackground: colors.cardBackground,
};
