import { colors } from "./colors";

export const lightColors = {
  background: colors.neutral50,
  text: colors.neutral950,
  tabIcon: colors.tertiary400,
  tabIconFocused: colors.primary600,
  card: colors.neutral50,
  cardSecondary: colors.neutralSecondary,
  border: colors.neutral200,
  icon: colors.neutral950,
  enabled: colors.primary600,
  disabled: colors.neutral200,
  light: colors.neutral50,
  dark: colors.neutral950,
  lightGreen: colors.lightGreen,
  mediumGreen: colors.mediumGreen,
  darkGreen: colors.darkGreen,
  lightBlue: colors.lightBlue,
  mediumBlue: colors.mediumBlue,
  darkBlue: colors.darkBlue,
  lightRed: colors.lightRed,
  mediumRed: colors.mediumRed,
  darkRed: colors.darkRed,
  info: colors.info,
  success: colors.success,
  warning: colors.warning,
  danger: colors.danger,
  white: colors.white,
  black: colors.black,
  tintColor: colors.tintColorLight,
  gold: colors.gold,
  cardBackground: colors.cardBackground,
};
